@extends('layouts.app')
@section('content')
@include('pages.customer_sessions._styles')
<div class="ao-training"><div class="ao-wrap">
@include('pages.customer_sessions._toolbar')
@if(session('success'))<div class="ao-alert ao-alert-success">{{ session('success') }}</div>@endif
@if(session('error'))<div class="ao-alert ao-alert-error">{{ session('error') }}</div>@endif
@if($errors->any())<div class="ao-alert ao-alert-error">{{ $errors->first() }}</div>@endif
<div class="mb-4"><div class="ao-eyebrow">ACCOUNT SETTINGS</div><h1 class="ao-section-title">Parent Profile & Players</h1></div>
<div class="ao-grid-2 mb-4"><section class="ao-panel p-4"><h2 style="font-weight:900">Parent Profile</h2><form method="POST" action="{{ route('em.customer.profile.update') }}" enctype="multipart/form-data">@csrf
<div class="ao-grid-2 mb-3"><div class="ao-field"><label>First Name *</label><input class="ao-input" name="first_name" value="{{ old('first_name',$customer->first_name) }}" required></div><div class="ao-field"><label>Last Name</label><input class="ao-input" name="last_name" value="{{ old('last_name',$customer->last_name) }}"></div></div>
<div class="ao-field mb-3"><label>Email *</label><input class="ao-input" type="email" name="email" value="{{ old('email',$customer->email) }}" required></div><div class="ao-field mb-3"><label>Phone</label><input class="ao-input" name="phone" value="{{ old('phone',$customer->phone) }}"></div><div class="ao-field mb-3"><label>Profile Photo</label><input class="ao-input" type="file" name="profile_photo" accept="image/*"></div>
<hr><h3 style="font-weight:900;font-size:18px">Change Password</h3><div class="ao-field mb-3"><label>Current Password</label><input class="ao-input" type="password" name="current_password"></div><div class="ao-grid-2 mb-3"><div class="ao-field"><label>New Password</label><input class="ao-input" type="password" name="password"></div><div class="ao-field"><label>Confirm New Password</label><input class="ao-input" type="password" name="password_confirmation"></div></div><button class="ao-btn ao-btn-red">Save Profile</button></form></section>
<section class="ao-panel p-4"><div class="d-flex justify-content-between align-items-center gap-3"><div><h2 style="font-weight:900;margin:0">Players</h2><p class="ao-muted mb-0">Players linked to this parent account.</p></div><button class="ao-btn ao-btn-red ao-btn-sm" data-bs-toggle="modal" data-bs-target="#addPlayer">Add Player</button></div>
@forelse($children as $child)<div class="ao-order-card"><div class="d-flex justify-content-between gap-3"><div><strong>{{ trim($child->first_name.' '.$child->last_name) }}</strong><div class="ao-muted">{{ collect([$child->team,$child->grade,$child->position])->filter()->implode(' · ') ?: 'Player' }}</div></div><div class="d-flex gap-2"><button class="ao-btn ao-btn-outline ao-btn-sm" data-bs-toggle="modal" data-bs-target="#editPlayer{{ $child->id }}">Edit</button><form method="POST" action="{{ route('em.customer.profile.children.delete',$child) }}" onsubmit="return confirm('Remove this player?')">@csrf @method('DELETE')<button class="ao-btn ao-btn-outline ao-btn-sm" style="color:#b42318">Remove</button></form></div></div></div>
<div class="modal fade" id="editPlayer{{ $child->id }}" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content ao-modal-card"><div class="ao-modal-head"><strong>Edit Player</strong><button class="btn-close btn-close-white" data-bs-dismiss="modal"></button></div><div class="modal-body p-4"><form method="POST" action="{{ route('em.customer.profile.children.update',$child) }}">@csrf @method('PUT') @include('pages.customer_sessions.player-fields',['player'=>$child])<div class="d-flex justify-content-end gap-2 mt-4"><button type="button" class="ao-btn ao-btn-outline" data-bs-dismiss="modal">Cancel</button><button class="ao-btn ao-btn-red">Save Player</button></div></form></div></div></div></div>
@empty<div class="text-center p-5"><i class="fa-solid fa-user-plus fa-2x mb-2" style="color:#f3282c"></i><p class="ao-muted">No players added yet.</p></div>@endforelse</section></div>
</div></div>
<div class="modal fade" id="addPlayer" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content ao-modal-card"><div class="ao-modal-head"><strong>Add Player</strong><button class="btn-close btn-close-white" data-bs-dismiss="modal"></button></div><div class="modal-body p-4"><form method="POST" action="{{ route('em.customer.profile.children.store') }}">@csrf @include('pages.customer_sessions.player-fields',['player'=>null])<div class="d-flex justify-content-end gap-2 mt-4"><button type="button" class="ao-btn ao-btn-outline" data-bs-dismiss="modal">Cancel</button><button class="ao-btn ao-btn-red">Add Player</button></div></form></div></div></div></div>
@endsection
