@extends('pages.customer_sessions.portal.layout')
@section('title','My Training Bookings | ACES Lacrosse')
@section('content')
<style>
.mb-tabs{display:inline-flex;background:#fff;border:1px solid rgba(97,30,178,.10);border-radius:999px;padding:5px;margin-bottom:18px;box-shadow:0 8px 22px rgba(48,27,65,.04)}.mb-tab{border:0;background:transparent;border-radius:999px;padding:10px 16px;font-size:12px;font-weight:900;color:#667085}.mb-tab.active{background:#611eb2;color:#fff;box-shadow:0 8px 22px rgba(97,30,178,.24)}.mb-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.mb-card{overflow:hidden;border:1px solid rgba(97,30,178,.10);border-radius:22px;background:radial-gradient(circle at top right,rgba(97,30,178,.08),transparent 34%),#fff;box-shadow:0 12px 28px rgba(48,27,65,.05)}.mb-head{display:flex;justify-content:space-between;gap:14px;padding:17px;border-bottom:1px solid rgba(97,30,178,.08)}.mb-head h3{margin:0;font-family:'Roboto',Arial,sans-serif;font-size:24px;font-weight:900;letter-spacing:-.04em}.mb-no{display:block;margin-top:5px;font-size:9px;font-weight:900;letter-spacing:.12em;color:#667085}.mb-date{min-width:66px;border-radius:18px;background:#171021;color:#fff;text-align:center;padding:8px}.mb-date strong{display:block;color:#c897ff;font-size:25px;line-height:1}.mb-date span{font-size:10px;font-weight:900}.mb-body{padding:16px}.mb-details{display:grid;grid-template-columns:1fr 1fr;gap:10px}.mb-detail{padding:11px;border-radius:14px;background:#f7f6f9}.mb-detail span{display:block;color:#667085;font-size:9px;font-weight:900;letter-spacing:.12em;text-transform:uppercase}.mb-detail strong{display:block;margin-top:5px;font-size:12px}.mb-detail.full{grid-column:1/-1}.mb-status{display:inline-flex;margin-top:12px;padding:6px 10px;border-radius:999px;background:#ecfdf3;color:#166534;font-size:10px;font-weight:900;text-transform:uppercase}.mb-actions{display:flex;gap:8px;margin-top:13px}.mb-actions a,.mb-actions button{border:0;border-radius:999px;padding:9px 13px;font-size:11px;font-weight:900;text-decoration:none}.mb-map{background:#171021;color:#fff}.mb-map:hover{background:#611eb2;color:#fff}.mb-cancel{background:#fff1f2;color:#b42318;border:1px solid #fecdd3!important}.mb-empty{padding:50px;text-align:center;border:2px dashed rgba(97,30,178,.14);border-radius:22px;color:#667085;background:#fff}@media(max-width:900px){.mb-grid{grid-template-columns:1fr}}
</style>
<div class="mb-tabs"><button class="mb-tab active" type="button" data-filter="upcoming"><i class="fa-regular fa-calendar-check me-1"></i>Upcoming ({{ $upcomingBookings->count() }})</button><button class="mb-tab" type="button" data-filter="past"><i class="fa-solid fa-clock-rotate-left me-1"></i>Past ({{ $pastBookings->count() }})</button></div>
@php $groups=['upcoming'=>$upcomingBookings,'past'=>$pastBookings]; @endphp
@foreach($groups as $key=>$items)
<div class="mb-panel" data-panel="{{ $key }}" @if($key!=='upcoming') hidden @endif>
@if($items->isEmpty())<div class="mb-empty">No {{ $key }} Training bookings.</div>@else<div class="mb-grid">
@foreach($items as $booking)
@php
$s=$booking->sessionEvent;$c=$booking->child;$date=$s&&$s->event_date?\Carbon\Carbon::parse($s->event_date):null;$start=$s&&$s->start_time?\Carbon\Carbon::parse($s->start_time)->format('g:i A'):'-';$end=$s&&$s->end_time?\Carbon\Carbon::parse($s->end_time)->format('g:i A'):'-';$title=$s?($s->training_type?:$s->name):'Training';$player=trim(($c->first_name??$booking->player_first).' '.($c->last_name??$booking->player_last));$location=$s?($s->location?:trim(($s->street_address??'').' '.($s->city??''))):'-';
@endphp
<article class="mb-card"><div class="mb-head"><div><h3>{{ $title }}</h3><span class="mb-no">{{ $booking->booking_no }}</span></div>@if($date)<div class="mb-date"><strong>{{ $date->format('d') }}</strong><span>{{ strtoupper($date->format('M')) }}</span></div>@endif</div><div class="mb-body"><div class="mb-details"><div class="mb-detail"><span>Date</span><strong>{{ $date?$date->format('l, M d, Y'):'-' }}</strong></div><div class="mb-detail"><span>Time</span><strong>{{ $start }} - {{ $end }}</strong></div><div class="mb-detail"><span>Player</span><strong>{{ $player?:'Player' }}</strong></div><div class="mb-detail"><span>Location</span><strong>{{ $location?:'-' }}</strong></div><div class="mb-detail full"><span>What to bring</span><strong>{{ $s->what_to_bring??'-' }}</strong></div></div><span class="mb-status">{{ str_replace('_',' ',$booking->status) }}</span><div class="mb-actions">@if($location)<a class="mb-map" target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query={{ urlencode($location) }}"><i class="fa-solid fa-map-location-dot me-1"></i>Open Map</a>@endif @if($key==='upcoming' && in_array($booking->status,['pending_payment','booked','paid'],true))<form method="POST" action="{{ route('em.customer.booking.cancel',$booking->id) }}" onsubmit="return confirm('Cancel this Training booking?')">@csrf<button class="mb-cancel" type="submit"><i class="fa-regular fa-trash-can me-1"></i>Cancel</button></form>@endif</div></div></article>
@endforeach
</div>@endif
</div>
@endforeach
@endsection
@push('scripts')<script>document.addEventListener('DOMContentLoaded',function(){document.querySelectorAll('.mb-tab').forEach(function(btn){btn.addEventListener('click',function(){document.querySelectorAll('.mb-tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.mb-panel').forEach(p=>p.hidden=p.dataset.panel!==btn.dataset.filter)})})});</script>@endpush
