@extends('admin.layouts.app')
@section('title','Dashboard')
@section('page-title','Dashboard')
@section('content')
<div class="row g-3 mb-3">
    <div class="col-12 col-sm-6 col-xl-3"><div class="kpi-card"><div class="kpi-icon"><i class="fa-solid fa-user-group"></i></div><div><div class="kpi-label">Total Parents</div><div class="kpi-value">{{ number_format($totalParents) }}</div><div class="kpi-meta"><i class="fa-solid fa-arrow-up"></i> Active parent accounts</div></div></div></div>
    <div class="col-12 col-sm-6 col-xl-3"><div class="kpi-card"><div class="kpi-icon"><i class="fa-solid fa-user-shield"></i></div><div><div class="kpi-label">Total Players</div><div class="kpi-value">{{ number_format($totalPlayers) }}</div><div class="kpi-meta"><i class="fa-solid fa-arrow-up"></i> Active players</div></div></div></div>
    <div class="col-12 col-sm-6 col-xl-3"><div class="kpi-card"><div class="kpi-icon"><i class="fa-regular fa-calendar-check"></i></div><div><div class="kpi-label">Total Bookings</div><div class="kpi-value">{{ number_format($totalBookings) }}</div><div class="kpi-meta"><i class="fa-solid fa-arrow-up"></i> Confirmed bookings only</div></div></div></div>
    <div class="col-12 col-sm-6 col-xl-3"><div class="kpi-card"><div class="kpi-icon"><i class="fa-solid fa-dollar-sign"></i></div><div><div class="kpi-label">Pending Payments</div><div class="kpi-value">${{ number_format($pendingPayments,2) }}</div><div class="kpi-meta"><i class="fa-solid fa-circle"></i> Awaiting completion</div></div></div></div>
</div>
<div class="dashboard-grid">
    <div class="dashboard-main">
        <div class="admin-card mb-3"><div class="admin-card-header"><h2>Bookings Overview</h2><select class="form-select form-select-sm" style="width:135px"><option>Last 30 Days</option></select></div><div class="chart-wrap"><canvas id="bookingsChart"></canvas></div></div>
        <div class="admin-card"><div class="admin-card-header"><h2>Recent Bookings</h2>@if(auth()->user()->hasAdminPermission('admin_privilages'))<a href="{{ route('admin.bookings.session-wise') }}" class="btn btn-sm btn-outline-primary">View All Bookings <i class="fa-solid fa-chevron-right ms-2"></i></a>@endif</div><div class="table-responsive"><table class="table admin-table mb-0"><thead><tr><th>#</th><th>Parent</th><th>Player</th><th>Session</th><th>Date</th><th>Status</th><th>Amount/Credit</th></tr></thead><tbody>@forelse($recentBookings as $booking)<tr><td data-label="#">{{ $loop->iteration }}</td><td data-label="Parent">{{ $booking->customer?->full_name ?: '—' }}</td><td data-label="Player">{{ $booking->child?->full_name ?: trim($booking->player_first.' '.$booking->player_last) ?: '—' }}</td><td data-label="Session">{{ $booking->sessionEvent?->name ?: '—' }}</td><td data-label="Date">{{ optional($booking->sessionEvent?->event_date)->format('M d, Y') ?: '—' }}</td><td data-label="Status"><span class="status-badge badge-soft-success">{{ ucwords(str_replace('_',' ',$booking->status)) }}</span></td><td data-label="Amount/Credit">{{ $booking->credit_id ? '1 class' : '—' }}</td></tr>@empty<tr><td colspan="7" class="text-center text-secondary py-5">No bookings yet.</td></tr>@endforelse</tbody></table></div></div>
    </div>
    <aside class="dashboard-side">
        <div class="admin-card"><div class="admin-card-header"><h3><i class="fa-regular fa-calendar me-2"></i>Upcoming Sessions</h3>@if(auth()->user()->hasAdminPermission('admin_privilages'))<a class="text-primary text-decoration-none small fw-bold" href="{{ route('admin.em.sessions.index') }}">View All</a>@endif</div>@forelse($upcomingSessions as $session)@php($capacityUsed = (int) $session->booked_count)<div class="session-item"><div class="session-date"><span>{{ $session->event_date->format('M') }}</span><strong>{{ $session->event_date->format('d') }}</strong></div><div class="session-info"><strong>{{ $session->name }}</strong><small>{{ \Carbon\Carbon::parse($session->start_time)->format('g:i A') }} - {{ \Carbon\Carbon::parse($session->end_time)->format('g:i A') }}</small><small>{{ $session->location ?: trim($session->street_address.', '.$session->city,', ') ?: 'Location TBD' }}</small></div><span class="spots-left">{{ max(0,(int)$session->capacity-$capacityUsed) }} Spots Left</span></div>@empty<div class="empty-state py-4">No upcoming sessions.</div>@endforelse</div>
        <div class="admin-card"><div class="admin-card-header"><h3><i class="fa-solid fa-dollar-sign me-2"></i>Recent Payments</h3>@if(auth()->user()->hasAdminPermission('admin_privilages'))<a class="text-primary text-decoration-none small fw-bold" href="{{ route('admin.payments.index') }}">View All</a>@endif</div>@forelse($recentPayments as $payment)<div class="payment-item"><i class="fa-regular fa-circle-check payment-check"></i><div class="payment-info"><strong>{{ $payment->customer?->full_name ?: $payment->name_on_card ?: 'Customer' }}</strong><small>{{ $payment->transaction_id ?: $payment->gateway }}</small></div><span class="payment-date">{{ optional($payment->paid_at ?: $payment->created_at)->format('M d, Y') }}</span><span class="payment-amount">${{ number_format($payment->amount,2) }}</span></div>@empty<div class="empty-state py-4">No successful payments yet.</div>@endforelse</div>
        @if(auth()->user()->hasAdminPermission('admin_privilages'))<div class="admin-card"><div class="admin-card-header"><h3><i class="fa-solid fa-bolt me-2"></i>Quick Actions</h3></div><div class="quick-actions"><a class="quick-action" href="{{ route('admin.bookings.session-wise') }}"><div class="quick-action-icon"><i class="fa-regular fa-calendar-plus"></i></div>New Booking</a><a class="quick-action" href="{{ route('admin.parents.booking.index') }}"><div class="quick-action-icon"><i class="fa-solid fa-user-plus"></i></div>Add Parent</a><a class="quick-action" href="{{ route('admin.parents.booking.index') }}"><div class="quick-action-icon"><i class="fa-solid fa-child-reaching"></i></div>Add Player</a><a class="quick-action" href="{{ route('admin.payments.index') }}"><div class="quick-action-icon"><i class="fa-regular fa-credit-card"></i></div>Payments</a></div></div>@endif
    </aside>
</div>
@endsection
@push('scripts')
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script>
<script>
const ctx=document.getElementById('bookingsChart');if(ctx){new Chart(ctx,{type:'line',data:{labels:@json($chartLabels),datasets:[{label:'Bookings',data:@json($chartBookings),borderColor:'#f3282c',backgroundColor:'rgba(243,40,44,.10)',fill:true,tension:.35,borderWidth:2,pointRadius:0},{label:'Completed',data:@json($chartCompleted),borderColor:'#9aa1ad',backgroundColor:'rgba(154,161,173,.08)',fill:true,tension:.35,borderWidth:2,pointRadius:0}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'top',align:'start',labels:{usePointStyle:true,boxWidth:7,padding:18}}},scales:{x:{grid:{display:false},ticks:{maxTicksLimit:8}},y:{beginAtZero:true,grid:{color:'#edf0f3',borderDash:[3,3]},ticks:{precision:0}}}}})}
</script>
@endpush