@extends('admin.layouts.app')
@section('title','Edit User')
@section('content')
<div class="page-heading"><div><h2>Edit Admin User</h2><p>Update account information, reset the password, and manage group membership.</p></div><a class="btn btn-light border" href="{{ route('admin.users.index') }}"><i class="fa-solid fa-arrow-left me-2"></i>Back</a></div>
<div class="admin-card"><div class="admin-card-header"><h3>{{ $user->name }}</h3></div><div class="admin-card-body"><form method="POST" action="{{ route('admin.users.update',$user) }}">@csrf @method('PUT')
<div class="row g-3"><div class="col-md-6"><label class="form-label">Name *</label><input class="form-control" name="name" value="{{ old('name',$user->name) }}" required></div><div class="col-md-6"><label class="form-label">Email *</label><input class="form-control" type="email" name="email" value="{{ old('email',$user->email) }}" required></div><div class="col-md-6"><label class="form-label">New password</label><input class="form-control" type="password" name="password" minlength="6"><div class="form-text">Leave blank to keep the current password.</div></div><div class="col-md-6"><label class="form-label">Confirm new password</label><input class="form-control" type="password" name="password_confirmation" minlength="6"></div><div class="col-12"><label class="form-label">User Groups</label><div class="row g-2">@foreach($userGroups as $group)<div class="col-md-4"><label class="checkbox-card"><input class="form-check-input mt-1" type="checkbox" name="user_group_ids[]" value="{{ $group->id }}" @checked(in_array($group->id,$selectedGroupIds))><span><strong>{{ $group->name }}</strong><small class="d-block text-muted">{{ $group->slug }}</small></span></label></div>@endforeach</div></div></div>
<div class="d-flex justify-content-end gap-2 mt-4"><a class="btn btn-light border" href="{{ route('admin.users.index') }}">Cancel</a><button class="btn btn-primary px-4">Save User</button></div>
</form></div></div>
@endsection
