@extends('admin.layouts.app')
@section('title','Users')
@section('content')
<div class="page-heading"><div><h2>Admin Users</h2><p>Create admin accounts and assign one or more permission groups.</p></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#createUserModal"><i class="fa-solid fa-user-plus me-2"></i>New User</button></div>
<div class="admin-card"><div class="admin-card-header"><h3><i class="fa-solid fa-users text-primary me-2"></i>Users</h3><span class="text-muted small">{{ $users->count() }} users</span></div><div class="table-responsive"><table class="table admin-table"><thead><tr><th>User</th><th>Email</th><th>Groups</th><th>Admin Access</th><th>Created</th><th class="text-end">Actions</th></tr></thead><tbody>
@foreach($users as $user)
<tr><td data-label="User"><div class="d-flex align-items-center gap-2"><div class="avatar" style="width:38px;height:38px;border-width:2px">{{ strtoupper(substr($user->name,0,1)) }}</div><strong>{{ $user->name }}</strong></div></td><td data-label="Email">{{ $user->email }}</td><td data-label="Groups">@forelse($user->userGroups as $group)<span class="status-badge badge-soft-primary me-1 mb-1">{{ $group->name }}</span>@empty<span class="text-muted">No groups</span>@endforelse</td><td data-label="Admin Access"><span class="status-badge {{ $user->canAccessAdmin() ? 'badge-soft-success':'badge-soft-danger' }}">{{ $user->canAccessAdmin() ? 'Enabled':'Disabled' }}</span></td><td data-label="Created">{{ $user->created_at ? $user->created_at->format('m/d/Y') : '—' }}</td><td data-label="Actions"><div class="table-actions"><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.users.edit',$user) }}"><i class="fa-solid fa-pen"></i></a>@if((int)$user->id!==1 && auth()->id()!==$user->id)<form method="POST" action="{{ route('admin.users.destroy',$user) }}" class="confirm-delete">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="fa-solid fa-trash"></i></button></form>@endif</div></td></tr>
@endforeach
</tbody></table></div></div>

<div class="modal fade" id="createUserModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="POST" action="{{ route('admin.users.store') }}">@csrf
<div class="modal-header"><h5 class="modal-title">Create Admin User</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div>
<div class="modal-body"><div class="mb-3"><label class="form-label">Name *</label><input class="form-control" name="name" required></div><div class="mb-3"><label class="form-label">Email *</label><input class="form-control" type="email" name="email" required></div><div class="row g-3"><div class="col-md-6"><label class="form-label">Password *</label><input class="form-control" type="password" name="password" minlength="6" required></div><div class="col-md-6"><label class="form-label">Confirm *</label><input class="form-control" type="password" name="password_confirmation" minlength="6" required></div></div><div class="mt-3"><label class="form-label">User Groups</label><select class="form-select" name="user_group_ids[]" multiple size="{{ min(max($userGroups->count(),3),7) }}">@foreach($userGroups as $group)<option value="{{ $group->id }}">{{ $group->name }}</option>@endforeach</select><div class="form-text">Hold Ctrl/Cmd to select multiple groups.</div></div></div>
<div class="modal-footer"><button type="button" class="btn btn-light border" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Create User</button></div>
</form></div></div></div>
@endsection
