@extends('admin.layouts.app')
@section('title','Add Members')
@section('content')
<style>
.member-page{--accent:#f3282c;--soft:#fff0f0}.member-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;flex-wrap:wrap;margin-bottom:18px}.member-head h2{font-weight:900;margin:0}.member-head p{color:#64748b;margin:5px 0 0}.member-panel{background:#fff;border:1px solid #e2e8f0;border-radius:18px;padding:18px;box-shadow:0 10px 30px rgba(15,23,42,.04)}.member-filter{display:grid;grid-template-columns:1fr auto auto;gap:12px;align-items:end;background:linear-gradient(135deg,#fff,#fff7f7);border:1px solid #f8cecf;border-radius:16px;padding:14px;margin-bottom:16px}.member-input{height:42px;border:1px solid #d7dde6;border-radius:12px;padding:0 13px;width:100%}.member-input:focus{outline:0;border-color:var(--accent);box-shadow:0 0 0 3px rgba(243,40,44,.1)}.accent-btn{background:var(--accent);border-color:var(--accent);color:#fff;font-weight:800;border-radius:999px}.accent-btn:hover{background:#d91f23;color:#fff}.count-pill{background:var(--soft);color:var(--accent);font-weight:800;border-radius:999px;padding:8px 12px}.member-table th{font-size:11px;text-transform:uppercase;background:#f8fafc;white-space:nowrap}.member-table td{vertical-align:middle}.member-action{width:34px;height:34px;border-radius:8px;display:inline-flex;align-items:center;justify-content:center}.member-modal .modal-dialog{max-width:920px}.member-modal .modal-content{border:0;border-radius:22px;overflow:hidden;box-shadow:0 30px 90px rgba(0,0,0,.25)}.member-modal .modal-header{background:linear-gradient(135deg,#08090d,#2a1113);color:#fff;border:0}.member-modal .modal-body{background:#f8f9fb;max-height:70vh;overflow-y:auto}.member-modal .modal-footer{background:#fff}.section-label{font-weight:900;margin-bottom:12px}.parent-card{background:#fff;border:1px solid #dfe4eb;border-radius:16px;padding:14px;height:100%}.position-pills{display:flex;gap:8px;flex-wrap:wrap}.position-pill{border:1px solid #d8dde6;border-radius:999px;background:#fff;padding:8px 13px;font-weight:700}.position-pill input{margin-right:6px}.email-note{font-size:12px;font-weight:700;margin-top:6px}.email-note.found{color:#b45309}.email-note.selected{color:#15803d}.import-box{border:2px dashed #f2b2b4;background:#fff7f7;border-radius:16px;padding:18px}.preview-table{min-width:900px}.preview-table th{background:#101522;color:#fff;white-space:nowrap}.preview-table input{min-width:130px}.table-toolbar{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap;align-items:center;margin:10px 0}.small-muted{font-size:12px;color:#64748b}@media(max-width:767px){.member-filter{grid-template-columns:1fr}.member-modal .modal-dialog{margin:8px}.member-head .btn{width:100%}}
</style>
<div class="member-page">
    <div class="member-head"><div><h2>Add Members</h2><p>Create and manage players with Parent 1 / Parent 2 relationships.</p></div><div class="d-flex gap-2 flex-wrap"><button class="btn btn-outline-dark rounded-pill fw-bold" data-bs-toggle="modal" data-bs-target="#importModal"><i class="fa-solid fa-file-arrow-up me-2"></i>Import Members</button><button class="btn accent-btn px-4" data-bs-toggle="modal" data-bs-target="#addMemberModal"><i class="fa-solid fa-plus me-2"></i>Add New Member</button></div></div>
    @if(!empty($headers) && !empty($rows))
    <div class="member-panel mb-3"><div class="d-flex justify-content-between align-items-center gap-2 flex-wrap mb-3"><div><h5 class="fw-bold mb-1">Spreadsheet Preview</h5><div class="small-muted">{{ $originalFileName }} · {{ count($rows) }} row(s)</div></div><span class="count-pill">Review before import</span></div><form method="POST" action="{{ route('admin.parents.booking.import') }}">@csrf<div class="table-responsive"><table class="table table-bordered preview-table"><thead><tr>@foreach($headers as $i=>$header)<th><input class="form-control form-control-sm" name="headers[{{ $i }}]" value="{{ $header }}"></th>@endforeach</tr></thead><tbody>@foreach($rows as $r=>$row)<tr>@foreach($headers as $i=>$header)<td><input class="form-control form-control-sm" name="rows[{{ $r }}][{{ $i }}]" value="{{ $row[$i] ?? '' }}"></td>@endforeach</tr>@endforeach</tbody></table></div><div class="text-end mt-3"><button class="btn accent-btn px-4"><i class="fa-solid fa-file-import me-2"></i>Import {{ count($rows) }} Rows</button></div></form></div>
    @endif
    <div class="member-panel"><div class="member-filter"><div><label class="form-label fw-bold small">SEARCH MEMBERS</label><input id="memberSearch" class="member-input" placeholder="Player, team, parent, email or phone..."></div><div><label class="form-label fw-bold small">SHOW</label><select id="memberLength" class="member-input" style="min-width:110px"><option>10</option><option selected>25</option><option>50</option><option>100</option></select></div><button id="memberReset" class="btn btn-dark rounded-pill px-4" type="button">Reset</button></div><div class="table-toolbar"><span id="memberInfo" class="small-muted"></span><span class="count-pill"><span id="visibleMemberCount">{{ $savedChildren->count() }}</span> Members</span></div><div class="table-responsive"><table class="table table-bordered table-hover member-table" id="memberTable"><thead><tr><th>Player</th><th>Team</th><th>Grade</th><th>Position</th><th>Parent 1</th><th>Parent 2</th><th>Birthdate</th><th class="text-end">Actions</th></tr></thead><tbody>
        @forelse($savedChildren as $child)
            @php $rels=$child->parentRelations->sortByDesc('is_primary');$p1=optional($rels->firstWhere('is_primary',1))->customer;$p2=optional($rels->firstWhere('is_primary',0))->customer; @endphp
            <tr data-search="{{ strtolower(trim($child->full_name.' '.$child->team.' '.$child->spring_team.' '.$child->class_year.' '.$child->position.' '.optional($p1)->full_name.' '.optional($p1)->email.' '.optional($p1)->phone.' '.optional($p2)->full_name.' '.optional($p2)->email.' '.optional($p2)->phone)) }}"><td><strong>{{ $child->full_name }}</strong><div class="small-muted">#{{ $child->id }}</div></td><td>{{ $child->team ?: '—' }}@if($child->spring_team)<div class="small-muted">Spring: {{ $child->spring_team }}</div>@endif</td><td>{{ $child->class_year ?: '—' }}</td><td>{{ $child->position ?: '—' }}</td><td>@if($p1)<strong>{{ $p1->full_name }}</strong><div class="small-muted">{{ $p1->email }}<br>{{ $p1->phone }}</div>@else—@endif</td><td>@if($p2)<strong>{{ $p2->full_name }}</strong><div class="small-muted">{{ $p2->email }}<br>{{ $p2->phone }}</div>@else—@endif</td><td>{{ $child->birthdate ? $child->birthdate->format('m/d/Y') : '—' }}</td><td><div class="d-flex justify-content-end gap-2"><button class="btn btn-outline-primary member-action" data-bs-toggle="modal" data-bs-target="#editMember{{ $child->id }}"><i class="fa-solid fa-pen"></i></button><form method="POST" action="{{ route('admin.parents.booking.children.delete',$child) }}" onsubmit="return confirm('Delete this member?');">@csrf @method('DELETE')<button class="btn btn-outline-danger member-action"><i class="fa-solid fa-trash"></i></button></form></div></td></tr>
        @empty<tr><td colspan="8" class="text-center py-5 text-muted">No members found.</td></tr>@endforelse
        </tbody></table></div><div id="memberPagination" class="d-flex justify-content-end gap-1 mt-3"></div></div>
</div>
@foreach($savedChildren as $child)@php $rels=$child->parentRelations->sortByDesc('is_primary');$p1=optional($rels->firstWhere('is_primary',1))->customer;$p2=optional($rels->firstWhere('is_primary',0))->customer; @endphp<div class="modal fade member-modal" id="editMember{{ $child->id }}" tabindex="-1"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><form method="POST" action="{{ route('admin.parents.booking.children.update',$child) }}">@csrf @method('PUT')@include('admin.parents_booking.member-form',['modalTitle'=>'Edit Member','child'=>$child,'p1'=>$p1,'p2'=>$p2,'formId'=>'edit'.$child->id])</form></div></div></div>@endforeach
<div class="modal fade member-modal" id="addMemberModal" tabindex="-1"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><form method="POST" action="{{ route('admin.parents.booking.children.store') }}">@csrf @include('admin.parents_booking.member-form',['modalTitle'=>'Add New Member','child'=>null,'p1'=>null,'p2'=>null,'formId'=>'add'])</form></div></div></div>
<div class="modal fade" id="importModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content border-0 rounded-4"><form method="POST" enctype="multipart/form-data" action="{{ route('admin.parents.booking.upload') }}">@csrf<div class="modal-header"><h5 class="fw-bold mb-0">Import Members</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="import-box"><i class="fa-solid fa-file-excel fs-2 text-primary mb-2"></i><h6 class="fw-bold">Upload Excel or CSV</h6><p class="small text-muted">Supports .xlsx and .csv directly. If PhpSpreadsheet is installed, .xls is also supported.</p><input type="file" class="form-control" name="excel_file" accept=".xlsx,.xls,.csv,.txt" required></div></div><div class="modal-footer"><button type="button" class="btn btn-light border" data-bs-dismiss="modal">Cancel</button><button class="btn accent-btn">Preview File</button></div></form></div></div></div>
@endsection
@push('scripts')
<script>
(function(){const table=document.getElementById('memberTable');if(!table)return;const rows=[...table.tBodies[0].rows];const search=document.getElementById('memberSearch'),len=document.getElementById('memberLength'),pager=document.getElementById('memberPagination'),info=document.getElementById('memberInfo');let page=1;function render(){const q=(search.value||'').toLowerCase().trim();const filtered=rows.filter(r=>(r.dataset.search||r.innerText.toLowerCase()).includes(q));const size=parseInt(len.value)||25,pages=Math.max(1,Math.ceil(filtered.length/size));page=Math.min(page,pages);rows.forEach(r=>r.style.display='none');filtered.slice((page-1)*size,page*size).forEach(r=>r.style.display='');document.getElementById('visibleMemberCount').textContent=filtered.length;const from=filtered.length?(page-1)*size+1:0,to=Math.min(page*size,filtered.length);info.textContent=`Showing ${from} to ${to} of ${filtered.length} records`;pager.innerHTML='';for(let i=1;i<=pages;i++){const b=document.createElement('button');b.type='button';b.className='btn btn-sm '+(i===page?'btn-dark':'btn-outline-secondary');b.textContent=i;b.onclick=()=>{page=i;render()};pager.appendChild(b)}}search.oninput=()=>{page=1;render()};len.onchange=()=>{page=1;render()};document.getElementById('memberReset').onclick=()=>{search.value='';len.value='25';page=1;render()};render();
 document.querySelectorAll('[data-parent-email]').forEach(input=>{let timer;input.addEventListener('input',function(){clearTimeout(timer);const field=this,note=document.querySelector(`[data-email-note="${field.dataset.parentEmail}"]`),prefix=field.dataset.parentEmail,form=field.closest('form');if(!note)return;note.textContent='';if(!field.value.includes('@'))return;timer=setTimeout(async()=>{try{const res=await fetch(`{{ route('admin.parents.booking.parents.check-email') }}?email=${encodeURIComponent(field.value)}`,{headers:{Accept:'application/json'}});const data=await res.json();if(data.exists){const c=data.customer;form.querySelector(`[name="${prefix}_id"]`).value=c.id||'';form.querySelector(`[name="${prefix}_first_name"]`).value=c.first_name||'';form.querySelector(`[name="${prefix}_last_name"]`).value=c.last_name||'';form.querySelector(`[name="${prefix}_phone"]`).value=c.phone||'';note.textContent='Existing parent found and selected.';note.className='email-note selected';}else{form.querySelector(`[name="${prefix}_id"]`).value='';note.textContent='New parent will be created.';note.className='email-note found';}}catch(e){}},350)})});})();
</script>
@endpush
