@php $selectedPositions=collect(explode(',',(string)optional($child)->position))->map(fn($v)=>trim($v))->filter()->all(); @endphp
<div class="modal-header"><h5 class="modal-title fw-bold">{{ $modalTitle }}</h5><button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button></div>
<div class="modal-body">
    <div class="section-label">Child Details</div>
    <div class="row g-3"><div class="col-md-6"><label class="form-label fw-bold">First Name <span class="text-danger">*</span></label><input class="form-control" name="first_name" value="{{ old('first_name',optional($child)->first_name) }}" required></div><div class="col-md-6"><label class="form-label fw-bold">Last Name</label><input class="form-control" name="last_name" value="{{ old('last_name',optional($child)->last_name) }}"></div><div class="col-md-6"><label class="form-label fw-bold">Team</label><input class="form-control" name="team" value="{{ old('team',optional($child)->team) }}"></div><div class="col-md-6"><label class="form-label fw-bold">Spring Team</label><input class="form-control" name="spring_team" value="{{ old('spring_team',optional($child)->spring_team) }}"></div><div class="col-md-6"><label class="form-label fw-bold">Grade</label><input class="form-control" name="class_year" value="{{ old('class_year',optional($child)->class_year) }}"></div><div class="col-md-6"><label class="form-label fw-bold">Birthdate</label><input type="date" class="form-control" name="birthdate" value="{{ old('birthdate',optional(optional($child)->birthdate)->format('Y-m-d')) }}"></div></div>
    <div class="mt-3"><label class="form-label fw-bold">Positions</label><div class="position-pills">@foreach(['Attack','Middie','Defense','Goalie'] as $position)<label class="position-pill"><input type="checkbox" name="positions[]" value="{{ $position }}" @checked(in_array($position,$selectedPositions))>{{ $position }}</label>@endforeach</div></div>
    <div class="row g-3 mt-2">
        @foreach([['parent_one','Parent 1',true,$p1],['parent_two','Parent 2',false,$p2]] as [$prefix,$label,$required,$parent])
        <div class="col-md-6"><div class="parent-card"><h6 class="fw-bold">{{ $label }} @if($required)<span class="text-danger">*</span>@endif</h6><input type="hidden" name="{{ $prefix }}_id" value="{{ optional($parent)->id }}"><div class="row g-2"><div class="col-6"><label class="form-label">First Name</label><input class="form-control" name="{{ $prefix }}_first_name" value="{{ optional($parent)->first_name }}"></div><div class="col-6"><label class="form-label">Last Name</label><input class="form-control" name="{{ $prefix }}_last_name" value="{{ optional($parent)->last_name }}"></div><div class="col-12"><label class="form-label">Email @if($required)<span class="text-danger">*</span>@endif</label><input type="email" class="form-control" name="{{ $prefix }}_email" value="{{ optional($parent)->email }}" data-parent-email="{{ $prefix }}" @required($required)><div class="email-note" data-email-note="{{ $prefix }}"></div></div><div class="col-12"><label class="form-label">Phone</label><input class="form-control" name="{{ $prefix }}_phone" value="{{ optional($parent)->phone }}"></div></div></div></div>
        @endforeach
    </div>
</div>
<div class="modal-footer"><button type="button" class="btn btn-outline-secondary rounded-pill" data-bs-dismiss="modal">Close</button><button class="btn accent-btn px-4"><i class="fa-solid fa-check me-2"></i>Save Member</button></div>
